#creates a folder and gets into it
function mkcd {
    mkdir "$1"; cd "$1"; }

#gets into the last edited folder inside a folder
function lastedited {
    cd "$1"; cd $(ls -1tb | head -n1); }

#checks a text for duplicates.
function checktext {
    firstnum=$(cat "$1" | wc -l)
    uniqenum=$(cat "$1" | sort | uniq | wc -l)

    if [ $firstnum = $uniqenum ]
    then
        echo [+] NO DUPLICATES FOUND
    else
        dupnum=$(expr $firstnum - $uniqenum) 
        echo [?] "$dupnum" DUPLICATES FOUND
        echo [*] $1 can be found at "$1".old
        cp $1 "$1".old
        echo [*] replacing the duplicate free file with "$1"
        uniqefile=$(cat $1 | sort | uniq)
        echo $uniqefile | tr ' ' '\n' > $1
        echo [+] REPLACEMENT COMPLETED
    fi
}

#aliases
alias coding='lastedited ~/Documents/coding'
alias giox='python3 ~/Documents/scripts/giox/giox.py'
alias bkscr='cd ~/.local/share/bkscripts'
alias syntaxcheck='python3 ~/Documents/scripts/syntaxcheck.py'
