#creates a folder and gets into it
function mkcd {
    mkdir "$1"; cd "$1"; }

#gets into the last edited folder inside a folder
function lastedited {
    cd "$1"; cd $(ls -1tb | head -n1); }

#checks a text for duplicates.
function checktext {
    firstnum=$(cat "$1" | wc -l)
    uniqenum=$(cat "$1" | sort | uniq | wc -l)

    if [ $firstnum = $uniqenum ]
    then
        echo [+] NO DUPLICATES FOUND
    else
        dupnum=$(expr $firstnum - $uniqenum) 
        echo [?] "$dupnum" DUPLICATES FOUND
        echo [*] $1 can be found at "$1".old
        cp $1 "$1".old
        echo [*] replacing the duplicate free file with "$1"
        uniqefile=$(cat $1 | sort | uniq)
        echo $uniqefile | tr ' ' '\n' > $1
        echo [+] REPLACEMENT COMPLETED
    fi
}

#gets into the ~/Documents/scripts if $1 is not specified. if $1 specified gets into the scripts/$1
function scripts {
    cd ~/Documents/scripts
    if [ ! -z $1 ]; then
        cd $1; 
    fi; }

#aliases
alias coding='lastedited ~/Documents/coding'
alias giox='python3 ~/Documents/scripts/giox/giox.py'
alias bkscr='cd ~/.local/share/bkscripts'
alias syntaxcheck='python3 ~/Documents/scripts/syntaxcheck.py'

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'

    # Show the currently running command in the terminal title:
    # http://www.davidpashley.com/articles/xterm-titles-with-bash.html
    show_command_in_title_bar()
    {
        case "$BASH_COMMAND" in
            *\033]0*)
                # The command is trying to set the title bar as well;
                # this is most likely the execution of $PROMPT_COMMAND.
                # In any case nested escapes confuse the terminal, so don't
                # output them.
                ;;
            *)
                #echo -ne "\033]0;${USER}@${HOSTNAME}: ${BASH_COMMAND}\007"
                 echo -ne "\033]0;${PWD}: ${BASH_COMMAND}\007"

                ;;
        esac
    }
    trap show_command_in_title_bar DEBUG
    ;;
*)
    ;;
esac

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[34m\]: \w\[\033[00m$\] '
