"some basic configuration
set number
set ts=4
set autoindent
set expandtab
set showmatch
set tabstop=4
set softtabstop=4
set showcmd
set wildmenu
set showmatch
set incsearch
set hlsearch
set foldmethod=indent
set foldlevel=99
set rtp+=~/.vim/bundle/Vundle.vim
set nocompatible
set encoding=utf-8

let python_highlight_all = 1
syntax enable

"key mappings
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

"enable folding
nnoremap <space> za

" Remove all trailing whitespace by pressing F4
noremap <F4> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" docstrings of folded code
let g:SimpylFold_docstring_preview=1

" close autocompleteme window
let g:ycm_autoclose_preview_window_after_completion=1

"https://github.com/sjl/badwolf
colorscheme badwolf

"close nerdtree after opening a file
let NERDTreeQuitOnOpen = 1

"nerdtree shortcut
map <silent> <C-n> :NERDTreeToggle<CR>

"to prevent clash with youcompleteme, change snippet trigger
imap <C-F> <esc>a<Plug>snipMateNextOrTrigger
smap <C-F> <Plug>snipMateNextOrTrigger

" Vundle settings
call vundle#begin()
filetype off

Plugin 'gmarik/Vundle.vim'
Plugin 'tmhedberg/SimpylFold'               "for folding
Plugin 'vim-scripts/indentpython.vim'	    "indenting
Plugin 'scrooloose/syntastic'		        "syntax checker
Plugin 'scrooloose/nerdtree'		        "file tree
Plugin 'kien/ctrlp.vim'		   	            "searching
Plugin 'Valloric/YouCompleteMe'             "auto-completion
Plugin 'tpope/vim-surround'                 "editing brackets <cs{[ ysiw'>
Plugin 'MarcWeber/vim-addon-mw-utils'       "vim snipmate dependency
Plugin 'tomtom/tlib_vim'                    "vim snipmate dependency
Plugin 'garbas/vim-snipmate'                "enables snippets
Plugin 'pangloss/vim-javascript'            "javascript indentation&syntax support
Plugin 'Xuyuanp/nerdtree-git-plugin'  "what you have edited since last commit

call vundle#end()
filetype plugin indent on
