"basic configuration
set tabstop=4         "when vim sees a <TAB> it reads it like 4 spaces
set softtabstop=4     "<TAB> equals to 4 spaces in editing mode
set expandtab         "<TAB>s are spaces
set number            "shows the line numbers
set wildmenu          "visual autocomplete for command menu
set incsearch         "search as characters are entered
set hlsearch          "highlight the matches
set foldenable        "enable folding
set foldlevelstart=10 "open most folds by default
set foldmethod=indent " fold based on indent level

"enabling the syntax(adds color to main words and everything)
syntax enable

"define the <leader>
let mapleader=','

"show unwanted white space
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

"set a line to column 100
set colorcolumn=100

"turn off search highlight
nnoremap <leader>q :nohlsearch<CR>

"Remove all trailing whitespace by pressing F4
noremap <F4> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

"<z> open/closes folds
nnoremap <z> za

"toggle gundo(tree-undo mode)
nnoremap <leader>u :GundoToggle<CR>

"nerdtree shortcut
map <silent> <C-n> :NERDTreeToggle<CR>

"vim-expand-region mapping
map ' <Plug>(expand_region_expand)
map ; <Plug>(expand_region_shrink)

"exit/enter insert mode
inoremap cc <esc>

"window movements
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"close autocompleteme window
let g:ycm_autoclose_preview_window_after_completion=1

"close nerdtree after opening a file
let NERDTreeQuitOnOpen = 1

"vundle settings
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'		        "file tree
Plugin 'kien/ctrlp.vim'		   	            "searching
Plugin 'Valloric/YouCompleteMe'             "auto-completion
Plugin 'Xuyuanp/nerdtree-git-plugin'        "what you have edited since last commit
Plugin 'sjl/gundo.vim'                      "super undo
Plugin 'tpope/vim-surround'                 "switch the quotes
Plugin 'terryma/vim-expand-region'          "visual mode helper
Plugin 'scrooloose/nerdcommenter'           "comment helper

call vundle#end()            " required
filetype plugin indent on    " required

"github.com/sjl/badwolf
colorscheme badwolf
